import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { CanvasSpec } from './workspace';

export interface FontProfile {
  title?: string;
  body?: string;
  mono?: string;
}

export interface GenerationResult {
  pageIds: string[];
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function sanitizeFontName(fontName: string, fallback: string): string {
  const sanitized = fontName.replace(/[^\p{L}\p{N}\p{M} _-]/gu, '').trim();
  return sanitized.length > 0 ? sanitized : fallback;
}

function escapeCssString(value: string): string {
  return value.replace(/["\\]/g, '\\$&');
}

function buildPageFragment(pageId: string, prompt: string, canvasSpec: CanvasSpec, fontProfile?: FontProfile): string {
  const titleFont = `"${escapeCssString(sanitizeFontName(fontProfile?.title ?? 'Inter', 'Inter'))}"`;
  const bodyFont = `"${escapeCssString(sanitizeFontName(fontProfile?.body ?? 'Noto Sans', 'Noto Sans'))}"`;
  const safePrompt = escapeHtml(prompt || 'New Slide');
  return `
<section data-deck-root="true" data-page-id="${pageId}" data-canvas-spec="${canvasSpec.widthPx}x${canvasSpec.heightPx}">
  <div data-node-id="${pageId}-title" data-node-type="text" data-page-id="${pageId}" style="left:120px; top:120px; font-size:54px; font-family:${titleFont}; font-weight:600;">
    ${safePrompt}
  </div>
  <div data-node-id="${pageId}-body" data-node-type="text" data-page-id="${pageId}" style="left:120px; top:240px; font-size:28px; font-family:${bodyFont};">
    Generated by WeaveLight engine. Update this fragment via deck.patch.apply.
  </div>
</section>
`.trim();
}

export async function runGeneration(
  sessionPath: string,
  canvasSpec: CanvasSpec,
  prompt: string,
  fontProfile?: FontProfile,
): Promise<GenerationResult> {
  const pageId = `page-${Date.now()}`;
  const fragment = buildPageFragment(pageId, prompt, canvasSpec, fontProfile);
  const pagesDir = path.join(sessionPath, 'pages');
  await mkdir(pagesDir, { recursive: true });
  await writeFile(path.join(pagesDir, `${pageId}.html`), fragment, 'utf8');

  await mkdir(path.join(sessionPath, 'docs'), { recursive: true });
  await writeFile(
    path.join(sessionPath, 'docs', 'generation.json'),
    JSON.stringify({ prompt, fontProfile, canvasSpec, pageIds: [pageId] }, null, 2),
    'utf8',
  );

  return { pageIds: [pageId] };
}

export async function retryGenerationPage(
  sessionPath: string,
  pageId: string,
  canvasSpec: CanvasSpec,
  prompt: string,
  fontProfile?: FontProfile,
): Promise<GenerationResult> {
  const fragment = buildPageFragment(pageId, prompt, canvasSpec, fontProfile);
  await writeFile(path.join(sessionPath, 'pages', `${pageId}.html`), fragment, 'utf8');
  return { pageIds: [pageId] };
}
